name: nexus_portfolio
channels:
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - scikit-learn
  - jupyter
  - pip:
    - sweetviz  # Bonus: For automated reporting